import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-2 h-screen">
        <div className="bg-red-100">
          test
        </div>
        <div className="bg-green-100">
          <Image src='/img.jpg'  />
        </div>
      </main>
    </div>
  );
}
